### PR TITLE
GFX shader param texture

### PR DESCRIPTION
**Pull request by coolsoftrf**
### Explain the Pull Request
Implements issue https://github.com/Xaymar/obs-StreamFX/issues/5 in the following parts:

Parameter Types
- texture2d

Parameter UI Customization
- Enumerations
  - texture2d (as either a source drop-down or a media/image file picker)

Provides support for HLSL shaders to use additional textures other than automatic `InputA `and `InputB`.

Gives ability to use the following texture sources via `source` annotation provided to a variable of `texture2d` type:
- "source" - the property will show a drop-down with a list of all available sources in the project;
- "media" - the property will show a file picker with video file extension filter;
- "image" (or any other string including empty) - the property will show a file picker with image file extension filter;

### Why is this necessary?
This gives the user an ability to write his own shaders that utilize various textures without limitation to automatic InputA (and InputB for transitions).

### Checklist
- [x] I will become the maintainer for this part of code.
- [ ] I have tested this code on all supported Platforms.
  - [x] Windows 10
  - [ ] Linux
  - [ ] Mac OS

### Related Issues
- https://github.com/coolsoftrf/obs-StreamFX/issues/1

### ToDo:
Update user manual with `source` annotation for `texture2d` type

### CODE REVIEW

**Review by Xaymar — CHANGES_REQUESTED** [review]
Very impressive first pull request, I was not expecting to see someone else actually be serious about adding features to StreamFX. I've done a surface-level review of the code and while most parts are fine, there are some very problematic parts - some obvious, some only obvious if you've worked with OBS Studio for years. Overall, it is almost exactly what I imagined the Texture feature will be like.

When #131 ends up implemented, the entire feature will most likely be refactored again into something massively more powerful than before. While I do not personally like including OBS Studio sources as a core part of StreamFX's features, I don't really see an alternative that works well enough for now. Personally I'd prefer it if users had to create Video Sources themselves and use those as an input into filters, but I can see a use case for both things here. Maybe in the future I'll get my lazy ass to write a proper wrapper for FFmpeg's media capabilities, with all the things FFmpeg has to offer.

**Comment by Xaymar** [comment]
I might be blind, but I do not see enumerations being implemented by this. See existing parameters for what enumerations are.

**Review by Xaymar — CHANGES_REQUESTED** [review]
Noticed some rather obvious issues with your usage of `float4 Time`.

**Comment by coolsoftrf** [comment]
> I might be blind, but I do not see enumerations being implemented by this. See existing parameters for what enumerations are.

What semantics do you think it's supposed to have? The only way to define such enum values that I can see is to reference other textures, but that seems quite useless approach, don't you think?

**Comment by Xaymar** [comment]
Finally getting around to looking at this, this PR is a lot more messy than it first seemed.

- Some code had deduplication done on it, which should have been a separate PR entirely. This was not mentioned in the description of the PR, or even separated from the commit that contains the actually useful parts.
- Signal handlers are used instead of the calls to the source objects themselves, resulting a circular dependency. In testing, this has crashed in 15 different test cases.
- For no reason at all, the Time parameter now only updates if the developer enabled Profiling code. This is possibly a result from not reading the manual for Shaders and assuming the current behavior in the new example shaders is due to that code instead of first looking for errors in the shader.

**Review by Xaymar — APPROVED** [review]

**Comment by Xaymar** [comment]
I've spent a few days/weeks refactoring this code now, with the goal of improving things beyond what it was originally. There are some changes compared to the original PR, but it is mostly based on the ideas @coolsoftrf had implemented:

- A few parts of the code were de-duplicated, which reduced the binary size slightly on MSVC.
- Shader Parameters now support visible() and active() tracking, which allows for selective rendering of things only when necessary.
- It's now possible to retrieve the underlying obs_source_t* of a gfx::shader.
- It's now possible to retrieve the parent gfx::shader object of a gfx::shader::parameter.
- It's now possible to retrieve the shader file that was compiled for a gfx::shader::parameter.
- Shaders now have extra profiling code added to them for debugging/profiling.
- Some parts technically support sRGB, assuming anyone can figure out how to use that correctly.
- Shaders now support up to N texture parameters, where N is the amount of sampler/texture units the users GPU supports.
- Two examples which are not from obs-shaderfilter were added. The obs-shaderfilter examples were clearly marked as for use with obs-shaderfilter and not placed under a permissible license.

**Comment by Xaymar** [comment]
Windows CI is failing due to Code Signing not being available in PRs, not due to the code itself. Merging anyway.

**Pull request merged**
