### PR TITLE
Auto-Framing: Automatically keep your face in the frame!

### LINKED ISSUE #402: Face Tracking to take source crop into account
### Description
Would it be possible for the face tracking effect to take into account the cropping of a source when attempting to keep the face in frame? This would be very useful in situations where a source is being cropped to a different aspect ratio or where you just need the face tracking to move in a single axis instead of both x and y. I guess this could also be accomplished by being able to zoom the x and y axis separately and cropping the source to change the aspect ratio so the image isn't distorted.

As an example, in the attached image, the upper source is the whole camera frame, the lower source is the cropped version I want to use on an overlay. I have applied face tracking to the lower source, but since the tracking is based on the full camera view, it doesn't keep the face in frame, even though there is more image  available.
face tracking

### Checklist
- [ ] I am willing to pay someone to implement this feature.
- [x] This feature absolutely can't be done with already existing features.

### LINKED ISSUE #553: [BUG] RTX Face Tracking filter not functional
### Operating System

Windows 10 1903 and higher

### OBS Studio Version?

26.1

### StreamFX Version

0.10.0

### Expected Behavior

Can zoom, change stability and other options.

### Current Behavior

The  sliders don't change anything to the image, enabling and disabling filters do not cause anything to change.

### Steps to Reproduce the Bug

1. Install fresh OBS 26.1.1 on Windows 10 latest.
2. Install AR and Video NVIDIA SDK
3. Install StreamFX 0.10.0
4. Add video source.
5. Open source filter window.
6. Add NVIDIA Face Tracking
7. Move sliders.
8. Nothing is affected.

### OBS Studio Log

Ok this is a text box. There isn't a crash.

### OBS Studio Crash Log

_No response_

### Any additional Information we need to know?

_No response_

### PR DESCRIPTION
**Pull request by Xaymar**
### Explain the Pull Request
Adds a new Auto-Framing filter to replace the old very broken "NVIIDA Face Tracking" filter.

### Why is this necessary?
The old "NVIDIA Face Tracking" feature stopped working long ago, due to very poorly written and buggy code.

### Checklist
- [x] I will become the maintainer for this part of code.
- [x] I have tested this code on all supported Platforms.

### Related Issues

- #386 
- #402 
- #553

### CODE REVIEW

**Comment by LuminairPrime** [comment]
I was JUST checking what was up with this feature, so I'm glad to see it working again. Well done!

**Comment by LuminairPrime** [comment]
If it helps, I've tested the latest alpha at the top of the release page, and the face tracking is working perfectly for me.

**Comment by Xaymar** [comment]
@jessemillar There is no specific release schedule for StreamFX, and Testing features are usually available in Testing. Things will be done when it's done.

**Comment by jessemillar** [comment]
@Xaymar Thanks for the response! I'll try the alpha for now. No rush at all.

**Comment by hofst** [comment]
@Xaymar Thanks for the efforts, it is already working well in the current (pre-)release. I have sent a donation via Paypal into your direction!

I have observed two issues today:
- Everything works fine with full hd camera resolution. But the framing breaks if I switch my camera to 4k resolution: The frame seems off, the zoom is suddenly too strong and both the offset and padding settings suddenly do strange things :-(
- If I enable group mode, the picture jumps from time to time if one person is not recognized for a couple of frames. It would be nice if the frame only moved if a person is not recognized for multiple seconds. And if that happens, it would be nice if the frame moves smoothly instead of jumping.

Thanks again for your work!

**Comment by Xaymar** [comment]
> Everything works fine with full hd camera resolution. But the framing breaks if I switch my camera to 4k resolution: The frame seems off, the zoom is suddenly too strong and both the offset and padding settings suddenly do strange things :-(

I'm unable to reproduce the described behavior. All the settings appear to behave as expected with an increase or decrease in resolution.

> If I enable group mode, the picture jumps from time to time if one person is not recognized for a couple of frames. It would be nice if the frame only moved if a person is not recognized for multiple seconds. And if that happens, it would be nice if the frame moves smoothly instead of jumping.

[At the current moment, the life time of any tracked point is 0.5s scaled by the tracking frequency.](https://github.com/Xaymar/obs-StreamFX/blob/master/source/filters/filter-autoframing.cpp#L630-L657) You can control precisely how fast the frame snaps to the removal of a face with the Stability setting.

**Comment by hofst** [comment]
@Xaymar 
Thanks for the quick response. I tried to record my screen to demonstrate the problem but unfortunately, another problem occurred. I'm not sure if they are related. My obs project is at 1920p and my camera at 4k.
At the moment, the auto-framing selects a wrong frame (or in this case the upper left corner). However, if I add another effect, it works again. Also, the green-screen seems to not work after a couple of hours and I have to remove and re-add the effect so it works again. My only explanation is that there is some shared state between the nvidia filters and the effects influence/corrupt each other, especially with higher resolution.
Here is a recording to demonstrate it (I have added a blur filter for privacy)

https://user-images.githubusercontent.com/2535762/145086764-ecbbc5f9-1f1d-4e08-8d7f-fb9b66e0c507.mp4

:

**Comment by Xaymar** [comment]
@hofst Please report these as individual issues. This is still a pull request and won't be checked for potential bugs.

**Comment by hofst** [comment]
Sure, done: https://github.com/Xaymar/obs-StreamFX/issues/739

**Pull request merged**
