### PR TITLE
encoders/ffmpeg: Add support for AMD AMF encoders

### LINKED ISSUE #210: FFmpeg Encoders: Add AMD VCE/VCN H.264/H.265
### Description
Implement an FFmpeg integration for the AMD VCE/VCN H.264 and H.265 encoders for use in OBS Studio. This should not be a replacement for obs-amd-encoder, but it should complement it. Similar to the NVENC ones, options should be neatly grouped and no option should be hidden.

No fixes or workarounds should be applied on StreamFX's side - all fixes and workarounds should be done in FFmpeg itself in order to not bloat the code needlessly.

### Checklist

- [ ] I am willing to pay someone to implement this feature.
- [ ] This feature absolutely can't be done with already existing features.

### PR DESCRIPTION
**Pull request by Xaymar**
### Description
Adds support for the AMD Advanced Media Framework H.264 and H.265 encoders via FFmpeg. The majority of settings are supported, and the UI/UX experience mimics that of the NVENC implementation. Various settings are left out due to their complexity and should be controlled via the custom parameters field.

Answers to questions that people will have no matter what I do:

* AMD is not officially or inofficially supporting this or involved in this.
* AMD did not pay me a dime to start on this.
* AMD encoders have not improved much.
* I do not have any AMD hardware to test, this is purely based on the documentation available. I am not willing to delve into their own hardware to discover weird behavior that is undocumented, and will stick 100% to their documentation. Deal with it.

### CODE REVIEW

**Comment by Xaymar** [comment]
Answers to questions that people will have no matter what I do:

* AMD is not officially or inofficially supporting this or involved in this.
* AMD did not pay me a dime to start on this.
* AMD encoders have not improved much.
* I do not have any AMD hardware to test, this is purely based on the documentation available. I am not willing to delve into their own hardware to discover weird behavior that is undocumented, and will stick 100% to their documentation. Deal with it.

**Comment by as-com** [comment]
This AMF encoder has the same bug that is [exhibited in the original AMF plugin version 2.5.1 and beyond](https://github.com/obsproject/obs-amd-encoder/issues/400#issuecomment-659159322) where using the "full" color range in OBS results in a file tagged with "limited" color, leading to incorrect color reproduction in the output file.

Here is a file produced with AMF encoder plugin version 2.5.0: 
[2020-08-09 13-36-23.zip](https://github.com/Xaymar/obs-StreamFX/files/5048144/2020-08-09.13-36-23.zip)

And here is a file produced with this branch of StreamFX: 
[2020-08-09 13-36-34.zip](https://github.com/Xaymar/obs-StreamFX/files/5048146/2020-08-09.13-36-34.zip)

And here is the log file: https://obsproject.com/logs/UYscr5W301ePi2u-

I am using a Vega 56 with AMD driver version 20.4.2 and Windows 10 1909.

**Comment by Xaymar** [comment]
> This AMF encoder has the same bug that is exhibited in the original AMF plugin version 2.5.1 and beyond where using the "full" color range in OBS results in a file tagged with "limited" color, leading to incorrect color reproduction in the output file.

The FFmpeg implementation [sets the correct color range](https://github.com/Xaymar/obs-StreamFX/blob/master/source/ffmpeg/tools.cpp#L210), so this is not a bug with the plugin, but the driver. For driver issues, please report them to AMD (and optionally put some media pressure on them to fix it) - I can't do anything about them. The linked log file shows that the correct color range was given to FFmpeg, after which all the control leaves my hands.

**Comment by as-com** [comment]
The older version of the AMD encoder plugin (2.5.0) does not have the issue, so I’m pretty sure it’s not a driver problem. Could it be an issue with the AMF library?

**Comment by Xaymar** [comment]
> The older version of the AMD encoder plugin (2.5.0) does not have the issue, so I’m pretty sure it’s not a driver problem. Could it be an issue with the AMF library?

The AMF library is not used here, FFmpeg is being used. FFmpeg may be using AMF, but that is completely out of my control. This is a bug you have to report to AMD, not me.

**Comment by Xaymar** [comment]
### Known Issues:
* Logged values drastically mismatch actual settings, or are straight up nonsense.
* Random crashes during encoding. Likely to be AMDs fault as they happen in the driver.
* No advanced control over the encoder, also AMDs fault.

**Comment by Xaymar** [comment]
Moving this to a future release, when I figure out how to compile FFmpeg for OBS.

**Comment by sofiageo** [comment]
> 
> 
> Moving this to a future release, when I figure out how to compile FFmpeg for OBS.

I'm a bit confused about this, my OBS already shows hevc_amf (nvenc_hevc) before I install StreamFX. The quality looks OKish too, I've recorded a small [video](https://www.youtube.com/watch?v=qNjIQePSpRw) which is about 250MB for 2 minutes of recording. Does it mean it's already included in OBS ffmpeg?

After I installed StreamFX (both this and the normal version) I can also see HEVC AMF on the standard recording options, and when I use it I get a smaller file size output (140MB) but the quality and the colors is much much worse.

Shouldn't the AMF API be able to customize the encoder? I can see some documents available [here](https://github.com/GPUOpen-LibrariesAndSDKs/AMF/tree/master/amf/doc). In this case, is ffmpeg missing the ability to customize? Maybe what I'm saying is stupid but if nvenc_hevc creates a better quality video, could you find what it is and apply it to the StreamFX handler/encoder?

By the way I'm not sure if it's helpful but on Linux for my GPU (AMD 5700xt) I can see 3 profiles available for HEVC from the ffmpeg output via vaapi - main,main10,rext - and rext seems to be having the better compression output.

I'm happy to help with testing anything else needed.

**Comment by sofiageo** [comment]
Never mind, my OBS was stuck for some reason and I couldn't see the new encoders, I extracted the build files again and I can now see the new StreamFX encoders. I think the quality is similar with the obs ffmpeg - although the file is as big. Sorry for my misleading comment.

**Comment by sofiageo** [comment]
> 
> ### Known Issues:
> 
>     * Logged values drastically mismatch actual settings, or are straight up nonsense.

I've been doing a lot of experiments with the customization to reduce file size, I even managed to get a 50MB file of 4 minute 1080p@30 HEVC gameplay with decent quality, which is very cool. 

It looks like some logged values are indeed nonsense, but if I enable `Look ahead` from the UI the log will show `Look-Ahead: Disabled <Default>` But if I then set `-preanalysis=true` in the custom settings it will log `Look-Ahead: Enabled`

I have no idea if that affects the output yet, I just thought to report it here in case it helps.

**Comment by Xaymar** [comment]
No unexpected errors left. Same bug affects all ffmpeg encoders, will have to be fixed at a later point in time.

**Comment by zapoqx** [comment]
So reading after the notification, does this mean its now implemented in the current release? A little confused since I don't see a page yet.

**Comment by Xaymar** [comment]
It is in a future release.

**Pull request merged**
