### PR TITLE
Fix and improve building on Linux and with Clang

### LINKED ISSUE #29: Reduce warnings in GCC and Clang++
**Describe the bug**
There are a ton of warnings currently output by clang++ and gcc, ranging from actual errors in behavior to simple cosmetic changes. Work is being done to fix this in `clang-compatibility`. This may also be necessary for Linux and MacOS support (See #27 and #13).

### PR DESCRIPTION
**Pull request by Xaymar**
Fixes #29

### CODE REVIEW

**Comment by amicalmant** [comment]
Is this functional? I tried to compile a .so file and add it in the obs-plugins directory but only 5 effects appear in the filter panel (not 3D) and they crash anyway. So have you abandoned the idea to make it Linux-compatible? ;-)

**Comment by Xaymar** [comment]
You need to build together with OBS Studio to get the right layout for linux. If you build using the default layout, it installs in a way that is compatible with Windows only. I don't know why @OBSProject chose to make the layout different per platform, but I hope that once a plugin manager is done it will be easier.

These improvements were the result of other people, not myself. I personally have no interest in Linux until Debian and Ubuntu merge the kernel fix for Zen1 CPUs which causes hard lockups during high intensity workloads.

**Comment by amicalmant** [comment]
> You need to build together with OBS Studio to get the right layout for linux.

Thank you @Xaymar. I have no idea how to build both "together" but I will dig the issue and find out. If I succed I will share my new knowledge here or in the project's wiki.

Warm regards,
--
C.A.

**Comment by Xaymar** [comment]
Steps to build with OBS Studio are relatively simple.

1. Clone obs-studio
2. Clone obs-stream-effects into obs-studio/plugins (so that you end up with a obs-stream-effects directory with a CMakeLists.txt inside it)
3. Edit obs-studio/plugins/CMakeLists.txt and add the line `add_subdirectory(obs-stream-effects)`.

Take a look at my fork if you aren't sure what I meant with the entire thing: https://github.com/Xaymar/obs-studio/tree/xaymar-plugins/plugins

**Comment by amicalmant** [comment]
BINGO! 😃 Thank you... I will document and share my experience ASAP. 
OBS-Screen-Capture2019-10-03

**Pull request merged**
